### ISSUE TITLE
Hi Nikita can I use this code?

### ISSUE THREAD

**Issue by TakhirMirza** [nikolaev-n/CocktailPartySpeakerRecognition#1]

**Comment by nikitashvarts** [comment]
Hey! Glad to meet you here! Thanks for being interested in my project!
I'm so sorry for such a delay, haven't been here for a long time...

Of course you can fork my repo and even make something great! I've added a standard Apache 2.0 license, so feel free to clone!

**Comment by TakhirMirza** [comment]
Hi Nikita,
Spasibo za razreshenie. I am working on the project where we have to
separate monaural speech.
We have some progress.

    Thanks.
    Regards,
    Dr. T.Mirzaev
